import React from 'react';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { cn } from '../utils/cn';
import { Navbar } from '../components/Navbar';
import { Seo } from '../components/Seo';
import { useTranslation } from 'react-i18next';

export default function TermsOfService() {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const breadcrumbSchema = {
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://atmosmind.app/' },
      { '@type': 'ListItem', position: 2, name: 'Terms of Service', item: 'https://atmosmind.app/terms' },
    ],
  };

  const handleSearch = useCallback((cityName: string, lat: number, lng: number) => {
    const encoded = encodeURIComponent(cityName);
    navigate(`/weather/${encoded}`, { state: { cityName, latitude: lat, longitude: lng } });
  }, [navigate]);

  const handleLocationRequest = useCallback(() => {
    navigate('/');
  }, [navigate]);

  return (
    <div
      className={cn(
        'min-h-screen transition-all duration-700 ease-in-out',
        'bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950',
        'text-white'
      )}
    >
      <Seo
        title={String(t('terms.seoTitle', { defaultValue: 'Terms of Service - AtmosMind' }))}
        description={String(
          t('terms.seoDescription', {
            defaultValue: 'Read the Terms of Service for AtmosMind, including AI and weather data disclaimers.',
          })
        )}
        path="/terms"
        structuredData={breadcrumbSchema}
      />

      <div className="w-full px-4 pt-10 sm:px-5 md:px-8 lg:px-12">
        <Navbar onSearch={handleSearch} onLocationRequest={handleLocationRequest} />
      </div>

      <div className="max-w-5xl mx-auto px-4 pb-10 sm:px-5 md:px-8 lg:px-12">
        <motion.main
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          className={cn(
            'rounded-3xl border border-white/10 bg-black/30 backdrop-blur-md',
            'px-6 py-8 md:px-10 md:py-10'
          )}
        >
          <h1 className="text-3xl md:text-4xl font-semibold text-white/90 font-heading mb-8">
            {String(t('terms.title', { defaultValue: 'Terms of Service' }))}
          </h1>

          <p className="text-white/70 leading-8 mb-8">
            {String(
              t('terms.intro', {
                defaultValue:
                  'These Terms of Service govern your use of AtmosMind. By accessing or using the service, you agree to these terms.',
              })
            )}
          </p>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl md:text-2xl font-semibold text-white/85">
              {String(t('terms.serviceTitle', { defaultValue: 'Service Description' }))}
            </h2>
            <p className="text-white/70 leading-8">
              {String(
                t('terms.serviceBody', {
                  defaultValue:
                    'AtmosMind provides weather dashboards, city search, and AI-generated insights intended for general informational use. Weather data may be sourced from third-party providers and presented in different units and languages.',
                })
              )}
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl md:text-2xl font-semibold text-white/85">
              {String(t('terms.aiTitle', { defaultValue: 'AI-Generated Insights' }))}
            </h2>
            <p className="text-white/70 leading-8">
              {String(
                t('terms.aiBody', {
                  defaultValue:
                    'Some content is generated by AI. AI outputs may be inaccurate, incomplete, or outdated. You are responsible for verifying information before making decisions based on it.',
                })
              )}
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl md:text-2xl font-semibold text-white/85">
              {String(t('terms.noWarrantyTitle', { defaultValue: 'No Warranty' }))}
            </h2>
            <p className="text-white/70 leading-8">
              {String(
                t('terms.noWarrantyBody', {
                  defaultValue:
                    'AtmosMind is provided “as is” and “as available” without warranties of any kind. We do not guarantee accuracy, availability, or fitness for a particular purpose.',
                })
              )}
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl md:text-2xl font-semibold text-white/85">
              {String(t('terms.limitationTitle', { defaultValue: 'Limitation of Liability' }))}
            </h2>
            <p className="text-white/70 leading-8">
              {String(
                t('terms.limitationBody', {
                  defaultValue:
                    'To the maximum extent permitted by law, AtmosMind and its operators are not liable for any indirect, incidental, special, or consequential damages arising from your use of the service.',
                })
              )}
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl md:text-2xl font-semibold text-white/85">
              {String(t('terms.adsTitle', { defaultValue: 'Advertising' }))}
            </h2>
            <p className="text-white/70 leading-8">
              {String(
                t('terms.adsBody', {
                  defaultValue:
                    'AtmosMind may display advertising, including ads served by Google AdSense. Ads may use cookies or device identifiers to measure performance and, where permitted, personalize ads.',
                })
              )}
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl md:text-2xl font-semibold text-white/85">
              {String(t('terms.changesTitle', { defaultValue: 'Changes to These Terms' }))}
            </h2>
            <p className="text-white/70 leading-8">
              {String(
                t('terms.changesBody', {
                  defaultValue:
                    'We may update these Terms from time to time. Continued use of the service after changes become effective constitutes acceptance of the revised Terms.',
                })
              )}
            </p>
          </section>
        </motion.main>
      </div>
    </div>
  );
}
